In [1]:
import pandas as pd
import numpy as np

In [2]:
college = pd.read_csv('data/college.csv', index_col="INSTNM")
city = college['CITY']
city

INSTNM
Alabama A & M University                                            Normal
University of Alabama at Birmingham                             Birmingham
Amridge University                                              Montgomery
University of Alabama in Huntsville                             Huntsville
Alabama State University                                        Montgomery
                                                                ...
SAE Institute of Technology  San Francisco                      Emeryville
Rasmussen College - Overland Park                            Overland Park
National Personal Training Institute of Cleveland         Highland Heights
Bay Area Medical Academy - San Jose Satellite Location            San Jose
Excel Learning Center-San Antonio South                        San Antonio
Name: CITY, Length: 7535, dtype: object

In [3]:
city.loc['Alabama A & M University']

'Normal'

In [4]:
city[['Alabama A & M University','Alabama State University']] #시리즈 형식에서 index하면 시리즈 형식으로 나옴.

INSTNM
Alabama A & M University        Normal
Alabama State University    Montgomery
Name: CITY, dtype: object

In [5]:
city['Alabama State University':'Alabama A & M University'] #숫자처럼 인덱싱도 가능~!

Series([], Name: CITY, dtype: object)

# 불리언 배열을 이용한 masking

In [6]:
alabama_mask = city.isin(['Birmingham','Montgomery'])
city[alabama_mask]

INSTNM
University of Alabama at Birmingham                 Birmingham
Amridge University                                  Montgomery
Alabama State University                            Montgomery
Auburn University at Montgomery                     Montgomery
Birmingham Southern College                         Birmingham
South University-Montgomery                         Montgomery
Faulkner University                                 Montgomery
Herzing University-Birmingham                       Birmingham
Huntingdon College                                  Montgomery
Jefferson State Community College                   Birmingham
Lawson State Community College-Birmingham Campus    Birmingham
Samford University                                  Birmingham
Southeastern Bible College                          Birmingham
H Councill Trenholm State Community College         Montgomery
West Virginia University Institute of Technology    Montgomery
Virginia College-Birmingham                         Birmingham
Southeastern School of Cosmetology                  Birmingham
Strayer University-Alabama                          Birmingham
University of Phoenix-Alabama                       Birmingham
Virginia College-Montgomery                         Montgomery
Fortis College-Montgomery                           Montgomery
Fortis Institute-Birmingham                         Birmingham
Hair Academy                                        Montgomery
Brown Mackie College-Birmingham                     Birmingham
Nunation School of Cosmetology                      Birmingham
Troy University-Montgomery Campus                   Montgomery
Name: CITY, dtype: object

# 3. 행과 열 동시에 선택하기

위에서는 loc 과 iloc 을 이용해 행을 선택했습니다.

그런데 DF는 row 와 column 이 있기에, 한 차원을 더 선택할 수 있죠.


| df.iloc[row_index, column_index]

| df.loc[row_names, column_names]


아래의 예를 봅시다.

In [7]:
college.iloc[:3,:4] #0,1,2번째 행 / 0,1,2,3 번째 열

                                           CITY STABBR  HBCU  MENONLY
INSTNM
Alabama A & M University                 Normal     AL   1.0      0.0
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0
Amridge University                   Montgomery     AL   0.0      0.0

In [8]:
college.iloc[:,[4,6]].head() #4번째, 6번째 열도 선택 가능!

                                     WOMENONLY  SATVRMID
INSTNM
Alabama A & M University                   0.0     424.0
University of Alabama at Birmingham        0.0     570.0
Amridge University                         0.0       NaN
University of Alabama in Huntsville        0.0     595.0
Alabama State University                   0.0     425.0

In [9]:
# 별도의 리스트로 관리하기 이 방법이 제일 깔끔함
rows = ['GateWay Community College', 'American Baptist Seminary of the West']
cols = ['MENONLY', 'RELAFFIL']

college.loc[rows, cols]

                                       MENONLY  RELAFFIL
INSTNM
GateWay Community College                  0.0         0
American Baptist Seminary of the West      0.0         1

In [10]:
# 슬라이싱의 세 번째 옵션(step)
college.iloc[90:80:-2, 5]

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

# loc와 iloc 동시에 사용하기

In [11]:
college.columns.get_loc('UGDS_WHITE')

10

In [12]:
pd.Series(college.columns) #10번째 있는걸 확인!

0                   CITY
1                 STABBR
2                   HBCU
3                MENONLY
4              WOMENONLY
5               RELAFFIL
6               SATVRMID
7               SATMTMID
8           DISTANCEONLY
9                   UGDS
10            UGDS_WHITE
11            UGDS_BLACK
12             UGDS_HISP
13            UGDS_ASIAN
14             UGDS_AIAN
15             UGDS_NHPI
16             UGDS_2MOR
17              UGDS_NRA
18             UGDS_UNKN
19              PPTUG_EF
20              CURROPER
21               PCTPELL
22              PCTFLOAN
23               UG25ABV
24       MD_EARN_WNE_P10
25    GRAD_DEBT_MDN_SUPP
dtype: object

In [13]:
col_start = college.columns.get_loc('UGDS_WHITE')
col_end = college.columns.get_loc('UGDS_UNKN') + 1

college.iloc[:5, col_start:col_end]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [14]:
#여기서 row 를 고려해봅시다.

row_start = college.index[10]
row_end = college.index[15]

college.loc[row_start:row_end, 'UGDS_WHITE':'UGDS_UNKN']

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Birmingham Southern College,0.7983,0.1102,0.0195,0.0517,0.0102,0.0000,0.0051,0.0000,0.0051
Chattahoochee Valley Community College,0.4661,0.4372,0.0492,0.0127,0.0023,0.0035,0.0151,0.0000,0.0139
Concordia College Alabama,0.0280,0.8758,0.0373,0.0093,0.0000,0.0000,0.0031,0.0466,0.0000
South University-Montgomery,0.3046,0.6054,0.0153,0.0153,0.0153,0.0096,0.0000,0.0019,0.0326
Enterprise State Community College,0.6408,0.2435,0.0509,0.0202,0.0081,0.0029,0.0254,0.0012,0.0069
James H Faulkner State Community College,0.6979,0.2259,0.0320,0.0084,0.0177,0.0014,0.0152,0.0007,0.0009

In [15]:
col_sorted = college.sort_index()
col_sorted.loc['Sp':'Su'] #뒤죽박죽이면 안됨, sort 후에 슬라이싱!

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Spa Tech Institute-Ipswich,Ipswich,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,37.0,...,0.0000,0.0000,0.0541,0.4054,1,0.2656,0.3906,0.7907,21500,6333
Spa Tech Institute-Plymouth,Plymouth,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,153.0,...,0.0000,0.0000,0.2484,0.3399,1,0.3716,0.4266,0.6250,21500,6333
Spa Tech Institute-Westboro,Westboro,MA,0.0,0.0,0.0,0,NaN,NaN,0.0,90.0,...,0.0000,0.0000,0.0222,0.5778,1,0.3409,0.4545,0.6882,21500,6333
Spa Tech Institute-Westbrook,Westbrook,ME,0.0,0.0,0.0,0,NaN,NaN,0.0,240.0,...,0.0000,0.0000,0.0042,0.2542,1,0.4350,0.5093,0.5224,21500,6333
Spalding University,Louisville,KY,0.0,0.0,0.0,1,490.0,440.0,0.0,1227.0,...,0.0302,0.0016,0.0326,0.2502,1,0.4442,0.6725,0.3764,41700,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Studio Academy of Beauty,Chandler,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,332.0,...,0.0392,0.0000,0.0090,0.0000,1,0.5855,0.6218,0.5675,NaN,6333
Studio Jewelers,New York,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,55.0,...,0.0000,0.0364,0.0000,0.6000,1,0.0451,0.0902,0.8525,PrivacySuppressed,PrivacySuppressed
Stylemaster College of Hair Design,Longview,WA,0.0,0.0,0.0,0,NaN,NaN,0.0,77.0,...,0.0130,0.0000,0.0000,0.0000,1,0.8036,0.7024,0.4510,17000,13320
Styles and Profiles Beauty College,Selmer,TN,0.0,0.0,0.0,0,NaN,NaN,0.0,31.0,...,0.0000,0.0000,0.0000,0.0000,1,0.8182,0.7955,0.2400,PrivacySuppressed,PrivacySuppressed
Styletrends Barber and Hairstyling Academy,Rock Hill,SC,0.0,0.0,0.0,0,NaN,NaN,0.0,45.0,...,0.0000,0.0000,0.0000,0.5556,0,1.0000,1.0000,0.3529,PrivacySuppressed,9495.5

In [16]:
#만약에 거꾸로 정렬이 되어 있다면, 인덱싱도 거꾸로 해주면 됩니다.

col_sorted_reversed = college.sort_index(ascending=False)
col_sorted_reversed.loc['E':'B']

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Dyersburg State Community College,Dyersburg,TN,0.0,0.0,0.0,0,NaN,NaN,0.0,2001.0,...,0.0185,0.0010,0.0085,0.4423,1,0.4921,0.2493,0.3097,26800,7475
Dutchess Community College,Poughkeepsie,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,6885.0,...,0.0446,0.0129,0.0049,0.3312,1,0.2464,0.1936,0.1806,32500,10250
Dutchess BOCES-Practical Nursing Program,Poughkeepsie,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,155.0,...,0.0581,0.0000,0.0000,0.7548,1,0.5294,0.6275,0.5430,36500,9500
Durham Technical Community College,Durham,NC,0.0,0.0,0.0,0,NaN,NaN,0.0,4769.0,...,0.0182,0.0025,0.0457,0.6905,1,0.4495,0.1796,0.5961,27200,11069.5
Durham Beauty Academy,Durham,NC,0.0,0.0,0.0,0,NaN,NaN,0.0,78.0,...,0.0000,0.0000,0.0128,0.0000,1,0.5746,0.8134,0.4000,PrivacySuppressed,15332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bacone College,Muskogee,OK,0.0,0.0,0.0,1,398.0,428.0,0.0,939.0,...,0.0298,0.0000,0.0895,0.1140,1,0.9392,0.8920,0.1648,29700,26350
Babson College,Wellesley,MA,0.0,0.0,0.0,0,615.0,660.0,0.0,2107.0,...,0.0233,0.2682,0.0603,0.0000,1,0.1709,0.3727,0.0090,86700,27000
BJ's Beauty & Barber College,Auburn,WA,0.0,0.0,0.0,0,NaN,NaN,0.0,28.0,...,0.0714,0.0000,0.0714,0.0000,1,0.5192,0.6154,0.2917,NaN,PrivacySuppressed
BIR Training Center,Chicago,IL,0.0,0.0,0.0,0,NaN,NaN,0.0,2132.0,...,0.0000,0.0000,0.0000,0.1806,0,0.6700,0.6998,0.6741,PrivacySuppressed,15394
B M Spurr School of Practical Nursing,Glen Dale,WV,0.0,0.0,0.0,0,NaN,NaN,0.0,31.0,...,0.0000,0.0000,0.0000,0.0000,1,0.4722,0.0000,0.4444,PrivacySuppressed,PrivacySuppressed